### ISSUE TITLE
Signed app crashes on startup

### ISSUE THREAD

**Issue by johansatge** [alexeyst/node-webkit-macappstore#4]
Hi,

a few users have reported that the sandboxed app crashes on startup.

The error occurs with the current `0.11.5` binary.

I built a new binary based on nwjs `0.12.1`, but the problem remains for those users (same error).

(You can check the new binary [here](https://github.com/johansatge/node-webkit-macappstore/commits/binary-0.12.1) - I wanted to resolve this issue before submitting a pull request)

When the app is not signed, it runs smoothly.

---

Here is the error:

```
Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
```

Complete log file is available [here](https://paste.ee/p/SDhk4).

**Comment by johansatge** [comment]
Update: version `0.93` of [@trevorlinton](https://github.com/trevorlinton) (available [here](https://github.com/nwjs/nw.js/issues/936#issuecomment-43331980)) seems to have the same issue.

**Comment by alexeyst** [comment]
Hi @johansatge 

Sorry for the delay. Does the empty app crash, or a specific line of code causes this? For me, the regular nw app works well and doesn't crash here, so I wanted to double check.

**Comment by johansatge** [comment]
Hi,

the empty app crashes too.

On my machine it works well, it does not make debugging easy..

**Comment by alexeyst** [comment]
I see. I believe it is important to get access to that machine somehow, are you able to ask the user to share screen with you to test?

**Comment by banezaklan** [comment]
Hello, I have this issue right now. I am sure I was able to start signed app at some point, but when I try today it is crashing. I tried with fixed 0.11.5 for Mac App Store, and with a regular one, same result.
I can start unsigned without problems, but when I sign it, it starts to crash with the same result as mentioned here, EXC_BREAKPOINT (SIGTRAP). Any ideas what to do about it?

**Comment by johansatge** [comment]
Hi,

@alexeyst I had access to the machine for a short time but I did not know where to start, as my knowledge of the patch (and more globally, the whole objective-c stuff) is quite limited..

@banezaklan if you can reproduce the issue, it should be easier to debug, I hope Alexey will know how to get you on track and find what's going on !

(If you want to download and install the tools needed to apply the patch and compile the project by yourself, the [instructions](https://github.com/nwjs/nw.js/wiki/Building-nw.js) on the nw.js docs are easy to follow)

**Comment by johansatge** [comment]
@patr0nus also uses a [very similar patch](https://github.com/patr0nus/node-webkit-mas) for his app, maybe he ran into the same issue.

**Comment by banezaklan** [comment]
@johansatge  Thanks! This is my error report, looks the same as what you have seen...

https://www.dropbox.com/s/vhmk1b4l6l9ssz3/nw-crash-log-osx.txt?dl=0

**Comment by banezaklan** [comment]
When I try to run signed app's node-webkit binary directly this is what I get:

[1828:0617/134020:ERROR:mach_broker_mac.mm(142)] bootstrap_look_up: Permission denied (1100)
[1828:0617/134020:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[1827:0617/134027:FATAL:process_singleton_posix.cc(211)] Check failed: path.length() < arraysize(addr->sun_path). Socket path too long: /Users/bane/Library/Containers/com.a51.activecollab.timer/Data/Library/Application Support/activecollab-timer/S
*\* Unknown exception behavior: 0
[1]    1827 trace trap  activecollab-timer\ 0-11-5\ signed.app/Contents/MacOS/node-webkit

Could it be that the full path is used in a "socket path" ? I think that if I shortened app ID it would work, but for users with longer user name, this would still happen?

**Comment by banezaklan** [comment]
Hmmm, looks like this problem goes down all the way to Chromium source. 
https://code.google.com/p/chromium/issues/detail?id=469065

**Comment by alexeyst** [comment]
@banezaklan You got it, we need a shorter app ID. And I do think that this can happen with users with a longer name. For my app, I just have com.gcl.q to keep it short.

So, this brings us to an idea with @johansatge — can you get your app ID shorter and see if your users keep failing?

If that's it, we can look into fixing this together with NWjs team.

**Comment by banezaklan** [comment]
@alexeyst  FYI, I just tried signing with a shorter app ID, com.a51.t and now I can start the app without problems.  However, I created another user on my machine with a (really) long user name, and that made the string too long again:

[4865:0618/101154:FATAL:process_singleton_posix.cc(211)] Check failed: path.length() < arraysize(addr->sun_path). Socket path too long: /Users/branislav.zaklan.giga.mega.ultra.ludilo/Library/Containers/com.a51.t/Data/Library/Application Support/activecollab-timer/S

So, I think this confirms that even with shortening app ID it can still easily break for some users.

**Comment by johansatge** [comment]
Well done @banezaklan you got it...

> So, this brings us to an idea with @johansatge — can you get your app ID shorter and see if your users keep failing?

I also tried this on my app. Shortened my bundle ID from `22` chars to `10` and sent the signed app to one of my users: it opened perfectly.

Someone has posted a [fix](https://codereview.chromium.org/1132823003/) on the chromium topic @banezaklan has mentionned.
I will try to work from it and recompile the app by the end of the week.

Cheers

(So bad the crashes are caused by this silly issue - I read somewhere that using a short bundle ID was recommended, but I thought it was a good practice, not a requirement !)

**Comment by johansatge** [comment]
Hi,

It looks good, @alexeyst I have sent a [pull request](https://github.com/alexeyst/node-webkit-macappstore/pull/5) with the updated binary.
The app runs seamlessly, regardless of the bundle ID length.

If you want to wait for the MAS confirmation, I'll upload my updated app tomorrow. I will keep you informed about the status.

In the meatine you may want to test the binary by yourselves @alexeyst @banezaklan.

**Comment by alexeyst** [comment]
Thank you @johansatge, great work!

Yep, would be great to have it confirmed by Apple, so if you have it with them it'd be ideal! I will also try the new binary with my app, and if it all works out it would be an insanely good upgrade—with new major version and fixes.

Thank you for spending your time on this!

**Comment by banezaklan** [comment]
Thanks @johansatge ! 
Just couple questions. What about the deprecated APIs problem and Mac App Store? As far as I understand this was the main reason you went with the older version before, 0.11.5? 
Also ffmpegsumo.so has to be removed? Will that affect nw?

**Comment by johansatge** [comment]
Hi,

sorry for the delay !

The deprecated and private APIs are the main problem, this is why this repo still exists (and it looks like it will [not change](https://code.google.com/p/chromium/issues/detail?id=496049)). But it should not affect the app.

About the `ffmpegsumo.so` file, it is safer to remove it. I try to submit several versions of my app while keeping it; on most cases, it was rejected (it was accepted once, probably because the validation team wasn't paying attention).
Removing the file should not affect the app, except if you plan to embed videos or sounds.

---

I'm currently writing a [guide](https://github.com/johansatge/nwjs-macappstore) to gather all those informations. Comments are very welcome !

Cheers

**Comment by alexeyst** [comment]
@johansatge @banezaklan Actually @rogerwang once mentioned that he was interested in resolving this issue here: https://github.com/nwjs/nw.js/issues/3258, so hopefully it might get introduced as a separate build of NWjs for AppStore purposes.

@johansatge Your guide is fantastic, I think it is exactly what people will need. I will have a look at it in more detail, but it looks just great.

**Comment by alexeyst** [comment]
I opened a new issue in the NWjs to get this done, as one day it was accepted by Roger. https://github.com/nwjs/nw.js/issues/3609

Feel free to vote for it in there! Thank you.

**Comment by johansatge** [comment]
Let's close this :) (see the [pull request](https://github.com/alexeyst/node-webkit-macappstore/pull/5))

**Comment by essingh** [comment]
@alexeyst I've been trying to get the nwjs-macappstore-v0.12.3-osx-x64 version working but haven't had any luck (the app crashes). However I'm able to get your 12.2 version working using the same bundle id (per your comments from another issue) for all the helpers and app itself.. Do you see any reason why we shouldn't use your 12.2 binary for MAS submission? By the way, great work with all you've done getting node webkit working for the MAS - thanks!
